### ISSUE TITLE
testing after wagtail update

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/tempelhof#130]
* tried to add "Project" to landing page, does not accept my page links. Tells me "Aufgrund von Fehlern bei der Validierung konnte die Seite nicht gespeichert werden." 
* it seems that the "geplante Veröffentlichung" still not works. Should it by now? I remember that we tested it before and though if it does not work we should take it out some time. It's not urgent, through.

Apart from that I don't see anything broken.

**Comment by fuzzylogic2000** [comment]
- The project thing is a bit strange. If a ProjectPage is chosen it's working fine, but wagtail should only show the type of pages it accepts (like for the other page choosers). I wanted to fix that, but would break the existing ProjectBlocks when rewriting it. And I didn't get it to work differently. So, maybe I can try to add a helptext??
- Yeah, the second bit wasn't fixed and still isn't working. We could make an issue, so that if we ever work on this project again, we will see and maybe fix it.

**Comment by fuzzylogic2000** [comment]
Hmm, unfortunately the help text is also not shown.

**Comment by fuzzylogic2000** [comment]
Ha! I did find it after all!

**Comment by fuzzylogic2000** [comment]
No, I didn't quite find it after all. The fix was only when the block was saved once. When choosing a new page link, only the project pages are shown, but otherwise all pages are still shown. I also added a helptext and will close this issue with the merge nevertheless.
